from system.db import (
    user_db as users_db,
    members_db,
    news_db,
    papers_db,
    gallery_db,
    popup_db,
    auth_codes_db,
    discord_link_requests_db as discord_link_col,
    legacy_users_db as manager_users_db,
    user_logs_db,
    discord_notifications_db,
    webauthn_credentials_db,
    webauthn_challenges_db,
)

__all__ = [
    "users_db",
    "members_db",
    "news_db",
    "papers_db",
    "gallery_db",
    "popup_db",
    "auth_codes_db",
    "discord_link_col",
    "manager_users_db",
    "user_logs_db",
    "discord_notifications_db",
    "webauthn_credentials_db",
    "webauthn_challenges_db",
]
