module.exports = {
  apps: [
    {
      name: "homepage-dev",
      cwd: "/home/lab/knpu/homepage/server",
      script: "run.py",
      interpreter: "/home/lab/knpu/.venv/bin/python",
      watch: false,
      time: true,
      env: { MODE: "0", PORT: "18002" },
    },
    {
      name: "complaint-dev",
      cwd: "/home/lab/knpu/complaint/server",
      script: "run.py",
      interpreter: "/home/lab/knpu/.venv/bin/python",
      watch: false,
      time: true,
      env: { MODE: "0", PORT: "18003" },
    },
    {
      name: "manager_web-dev",
      cwd: "/home/lab/knpu/manager/web",
      script: "run.py",
      interpreter: "/home/lab/knpu/.venv/bin/python",
      watch: false,
      time: true,
      env: { MODE: "0", PORT: "18080" },
    },
    {
      name: "dashboard-dev",
      cwd: "/home/lab/knpu/admin",
      script: "run.py",
      interpreter: "/home/lab/knpu/.venv/bin/python",
      watch: false,
      time: true,
      env: { MODE: "0", PORT: "13004" },
    },
    {
      name: "manager-dev",
      cwd: "/home/lab/knpu/manager/server",
      script: "run.py",
      interpreter: "/home/lab/knpu/.venv/bin/python",
      watch: false,
      time: true,
      env: { MODE: "0", PORT: "18000" },
    },
    {
      name: "network-dev",
      cwd: "/home/lab/knpu/network",
      script: "run.py",
      interpreter: "/home/lab/knpu/.venv/bin/python",
      watch: false,
      time: true,
      env: { MODE: "0", PORT: "18001" },
    },
    {
      name: "kemkim-dev",
      cwd: "/home/lab/knpu/kemkim",
      script: "run.py",
      interpreter: "/home/lab/knpu/.venv/bin/python",
      watch: false,
      time: true,
      env: { MODE: "0", PORT: "18008" },
    },
    {
      name: "statistics-dev",
      cwd: "/home/lab/knpu/statistics",
      script: "run.py",
      interpreter: "/home/lab/knpu/.venv/bin/python",
      watch: false,
      time: true,
      env: { MODE: "0", PORT: "18009" },
    },
    {
      name: "ahp-dev",
      cwd: "/home/lab/knpu/ahp",
      script: "run.py",
      interpreter: "/home/lab/knpu/.venv/bin/python",
      watch: false,
      time: true,
      env: { MODE: "0", PORT: "18010" },
    },
  ],
};
