module.exports = {
  apps: [
    {
      name: "homepage-dev",
      cwd: "/home/wcchoi/knpu/homepage/server",
      script: "run.py",
      interpreter: "/home/wcchoi/knpu/.venv/bin/python",
      watch: false,
      time: true,
      env: { MODE: "0", PORT: "18000" },
    },
    {
      name: "manager-dev",
      cwd: "/home/wcchoi/knpu/manager/server",
      script: "run.py",
      interpreter: "/home/wcchoi/knpu/.venv/bin/python",
      watch: false,
      time: true,
      env: { MODE: "0", PORT: "18001" },
    },
    {
      name: "network-dev",
      cwd: "/home/wcchoi/knpu/network",
      script: "run.py",
      interpreter: "/home/wcchoi/knpu/.venv/bin/python",
      watch: false,
      time: true,
      env: { MODE: "0", PORT: "18003" },
    },
    {
      name: "kemkim-dev",
      cwd: "/home/wcchoi/knpu/kemkim",
      script: "run.py",
      interpreter: "/home/wcchoi/knpu/.venv/bin/python",
      watch: false,
      time: true,
      env: { MODE: "0", PORT: "18008" },
    },
    {
      name: "statistics-dev",
      cwd: "/home/wcchoi/knpu/statistics",
      script: "run.py",
      interpreter: "/home/wcchoi/knpu/.venv/bin/python",
      watch: false,
      time: true,
      env: { MODE: "0", PORT: "18004" },
    },
    {
      name: "manager_web-dev",
      cwd: "/home/wcchoi/knpu/manager/web",
      script: "run.py",
      interpreter: "/home/wcchoi/knpu/.venv/bin/python",
      watch: false,
      time: true,
      env: { MODE: "0", PORT: "18006" },
    },
    {
      name: "ahp-dev",
      cwd: "/home/wcchoi/knpu/ahp",
      script: "run.py",
      interpreter: "/home/wcchoi/knpu/.venv/bin/python",
      watch: false,
      time: true,
      env: { MODE: "0", PORT: "18007" },
    },
    {
      name: "complaint-dev",
      cwd: "/home/wcchoi/knpu/complaint/server",
      script: "run.py",
      interpreter: "/home/wcchoi/knpu/.venv/bin/python",
      watch: false,
      time: true,
      env: { MODE: "0", PORT: "18010" },
    },
    {
      name: "dashboard-dev",
      cwd: "/home/wcchoi/knpu/admin",
      script: "run.py",
      interpreter: "/home/wcchoi/knpu/.venv/bin/python",
      watch: false,
      time: true,
      env: { MODE: "0", PORT: "18009" },
    },
  ],
};
