module.exports = {
  apps: [
    {
      name: "homepage",
      cwd: "/home/lab/knpu/homepage/server",
      script: "run.py",
      interpreter: "/home/lab/knpu/.venv/bin/python",
      watch: true,
      time: true,
      env: { MODE: "1", PORT: "8002" },
    },
    {
      name: "complaint",
      cwd: "/home/lab/knpu/complaint/server",
      script: "run.py",
      interpreter: "/home/lab/knpu/.venv/bin/python",
      watch: true,
      time: true,
      env: { MODE: "1", PORT: "8003" },
    },
    {
      name: "manager_web",
      cwd: "/home/lab/knpu/manager/web",
      script: "run.py",
      interpreter: "/home/lab/knpu/.venv/bin/python",
      watch: true,
      time: true,
      env: { MODE: "1", PORT: "8080" },
    },
    {
      name: "dashboard",
      cwd: "/home/lab/knpu/admin",
      script: "run.py",
      interpreter: "/home/lab/knpu/.venv/bin/python",
      watch: true,
      time: true,
      env: { MODE: "1", PORT: "3004" },
    },
    {
      name: "manager",
      cwd: "/home/lab/knpu/manager/server",
      script: "run.py",
      interpreter: "/home/lab/knpu/.venv/bin/python",
      watch: false,
      time: true,
      env: { MODE: "1", PORT: "8000" },
    },
    {
      name: "network",
      cwd: "/home/lab/knpu/network",
      script: "run.py",
      interpreter: "/home/lab/knpu/.venv/bin/python",
      watch: false,
      time: true,
      env: { MODE: "1", PORT: "8001" },
    },
    {
      name: "kemkim",
      cwd: "/home/lab/knpu/kemkim",
      script: "run.py",
      interpreter: "/home/lab/knpu/.venv/bin/python",
      watch: false,
      time: true,
      env: { MODE: "1", PORT: "8008" },
    },
    {
      name: "statistics",
      cwd: "/home/lab/knpu/statistics",
      script: "run.py",
      interpreter: "/home/lab/knpu/.venv/bin/python",
      watch: false,
      time: true,
      env: { MODE: "1", PORT: "8009" },
    },
    {
      name: "ahp",
      cwd: "/home/lab/knpu/ahp",
      script: "run.py",
      interpreter: "/home/lab/knpu/.venv/bin/python",
      watch: false,
      time: true,
      env: { MODE: "1", PORT: "8010" },
    },
    {
      name: "bot",
      cwd: "/home/lab/knpu/system/bot",
      script: "run.py",
      interpreter: "/home/lab/knpu/.venv/bin/python",
      watch: true,
      time: true,
      env: { MODE: "1" },
    },
    {
      name: "gpu-tunnel",
      script: "/home/lab/bash/gpu_tunnel.sh",
      watch: true,
      time: true,
    },
  ],
};
